Epoch 1, true	ll: -1.4988	mae: 0.84409
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    main()
  File "main.py", line 302, in main
    _, best_ks = utils.kde_eval(model, val_data, config)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/utils.py", line 79, in kde_eval
    samples = model.sample(repeated_x, batch_size=config["eval_batch_size"]).reshape(
  File "/home/jupyter/papers/regressGAN/replication/CGAN/models/gp.py", line 66, in sample
    samples = self.gp.sample_y(unique_x, n_samples=n_samples, random_state=None)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/sklearn/gaussian_process/_gpr.py", line 403, in sample_y
    for i in range(y_mean.shape[1])]
  File "/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/sklearn/gaussian_process/_gpr.py", line 403, in <listcomp>
    for i in range(y_mean.shape[1])]
  File "mtrand.pyx", line 4084, in numpy.random.mtrand.RandomState.multivariate_normal
  File "<__array_function__ internals>", line 6, in svd
  File "/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1626, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
