2022-10-10 11:45:57,775 DEBUG   MainThread:19234 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-10 11:45:57,783 DEBUG   MainThread:19234 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-10 11:45:57,788 DEBUG   MainThread:19234 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-10 11:45:57,792 DEBUG   MainThread:19234 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-10 11:45:57,805 DEBUG   MainThread:19234 [run_manager.py:__init__():535] Initialized sync for cgan_regression/1ahw7m9y
2022-10-10 11:45:57,807 INFO    MainThread:19234 [run_manager.py:wrap_existing_process():1133] wrapping existing process 19186
2022-10-10 11:45:57,807 WARNING MainThread:19234 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-10 11:45:57,810 DEBUG   MainThread:19234 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-10 11:45:57,845 DEBUG   MainThread:19234 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-10 11:45:57,859 INFO    MainThread:19234 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-10 11:45:57,859 INFO    MainThread:19234 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-10 11:45:57,860 INFO    MainThread:19234 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-10 11:45:58,779 INFO    Thread-3  :19234 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221010_114557-1ahw7m9y/config.yaml
2022-10-10 11:57:10,586 INFO    MainThread:19234 [run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-10 11:57:10,587 INFO    MainThread:19234 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-10 11:57:10,587 INFO    MainThread:19234 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
nThread:19234 [1ahw7m9y:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-10 11:57:10,587 INFO    MainThread:19234 [1ahw7m9y:run_manager.py:shutdown():1057] shutting down system stats and metadata service
