2022-10-12 11:35:03,340 DEBUG   MainThread:1690 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-12 11:35:03,348 DEBUG   MainThread:1690 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-12 11:35:03,354 DEBUG   MainThread:1690 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-12 11:35:03,357 DEBUG   MainThread:1690 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-12 11:35:03,370 DEBUG   MainThread:1690 [run_manager.py:__init__():535] Initialized sync for cgan_regression/gypzyibc
2022-10-12 11:35:03,371 INFO    MainThread:1690 [run_manager.py:wrap_existing_process():1133] wrapping existing process 32330
2022-10-12 11:35:03,372 WARNING MainThread:1690 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-12 11:35:03,374 DEBUG   MainThread:1690 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-12 11:35:03,413 DEBUG   MainThread:1690 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-12 11:35:03,428 INFO    MainThread:1690 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-12 11:35:03,428 INFO    MainThread:1690 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-12 11:35:03,429 INFO    MainThread:1690 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-12 11:35:04,345 INFO    Thread-3  :1690 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221012_113502-gypzyibc/config.yaml
2022-10-12 11:39:04,114 INFO    MainThread:1690 [run_manager.py:_sync_etc():1313] process received interrupt signal, shutting down
2022-10-12 11:39:04,114 INFO    MainThread:1690 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-12 11:39:04,114 INFO    MainThread:1690 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
inThread:1690 [gypzyibc:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-12 11:39:04,114 INFO    MainThread:1690 [gypzyibc:run_manager.py:shutdown():1057] shutting down system stats and metadata service
