2022-10-12 13:25:40,977 DEBUG   MainThread:31123 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-12 13:25:40,984 DEBUG   MainThread:31123 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-12 13:25:40,989 DEBUG   MainThread:31123 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-12 13:25:40,993 DEBUG   MainThread:31123 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-12 13:25:41,005 DEBUG   MainThread:31123 [run_manager.py:__init__():535] Initialized sync for cgan_regression/a0lp3s5k
2022-10-12 13:25:41,007 INFO    MainThread:31123 [run_manager.py:wrap_existing_process():1133] wrapping existing process 31074
2022-10-12 13:25:41,007 WARNING MainThread:31123 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-12 13:25:41,010 DEBUG   MainThread:31123 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-12 13:25:41,048 DEBUG   MainThread:31123 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-12 13:25:41,063 INFO    MainThread:31123 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-12 13:25:41,063 INFO    MainThread:31123 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-12 13:25:41,063 INFO    MainThread:31123 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-12 13:25:41,982 INFO    Thread-3  :31123 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221012_132540-a0lp3s5k/config.yaml
2022-10-12 13:48:32,551 INFO    MainThread:31123 [run_manager.py:_sync_etc():1313] process received interrupt signal, shutting down
2022-10-12 13:48:32,551 INFO    MainThread:31123 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-12 13:48:32,552 INFO    MainThread:31123 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
nThread:31123 [a0lp3s5k:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-12 13:48:32,552 INFO    MainThread:31123 [a0lp3s5k:run_manager.py:shutdown():1057] shutting down system stats and metadata service
