2022-10-16 10:22:40,134 DEBUG   MainThread:25857 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-16 10:22:40,142 DEBUG   MainThread:25857 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-16 10:22:40,148 DEBUG   MainThread:25857 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-16 10:22:40,152 DEBUG   MainThread:25857 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-16 10:22:40,166 DEBUG   MainThread:25857 [run_manager.py:__init__():535] Initialized sync for cgan_regression/1i796ryo
2022-10-16 10:22:40,168 INFO    MainThread:25857 [run_manager.py:wrap_existing_process():1133] wrapping existing process 25765
2022-10-16 10:22:40,168 WARNING MainThread:25857 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-16 10:22:40,171 DEBUG   MainThread:25857 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-16 10:22:40,208 DEBUG   MainThread:25857 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-16 10:22:40,224 INFO    MainThread:25857 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-16 10:22:40,224 INFO    MainThread:25857 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-16 10:22:40,224 INFO    MainThread:25857 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-16 10:22:41,139 INFO    Thread-3  :25857 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221016_102239-1i796ryo/config.yaml
2022-10-16 12:33:52,569 INFO    MainThread:25857 [run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-16 12:33:52,569 INFO    MainThread:25857 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-16 12:33:52,569 INFO    MainThread:25857 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
nThread:21560 [6ygaa2bv:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-16 11:01:16,507 INFO    MainThread:21560 [6ygaa2bv:run_manager.py:shutdown():1057] shutting down system stats and metadata service
2022-10-16 12:14:06,831 INFO    MainThread:25715 [3m4zhpqn:run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-16 12:14:06,832 INFO    MainThread:25715 [3m4zhpqn:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-16 12:14:06,832 INFO    MainThread:25715 [3m4zhpqn:run_manager.py:shutdown():1057] shutting down system stats and metadata service
2022-10-16 12:33:52,569 INFO    MainThread:25857 [1i796ryo:run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-16 12:33:52,569 INFO    MainThread:25857 [1i796ryo:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-16 12:33:52,569 INFO    MainThread:25857 [1i796ryo:run_manager.py:shutdown():1057] shutting down system stats and metadata service
