2022-10-12 11:08:08,138 DEBUG   MainThread:1624 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-12 11:08:08,145 DEBUG   MainThread:1624 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-12 11:08:08,151 DEBUG   MainThread:1624 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-12 11:08:08,155 DEBUG   MainThread:1624 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-12 11:08:08,171 DEBUG   MainThread:1624 [run_manager.py:__init__():535] Initialized sync for cgan_regression/u1eg7o2s
2022-10-12 11:08:08,173 INFO    MainThread:1624 [run_manager.py:wrap_existing_process():1133] wrapping existing process 1575
2022-10-12 11:08:08,173 WARNING MainThread:1624 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-12 11:08:08,176 DEBUG   MainThread:1624 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-12 11:08:08,216 DEBUG   MainThread:1624 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-12 11:08:08,229 INFO    MainThread:1624 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-12 11:08:08,230 INFO    MainThread:1624 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-12 11:08:08,230 INFO    MainThread:1624 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-12 11:08:09,143 INFO    Thread-3  :1624 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221012_110807-u1eg7o2s/config.yaml
2022-10-12 11:29:11,912 INFO    MainThread:1624 [run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-12 11:29:11,913 INFO    MainThread:1624 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-12 11:29:11,913 INFO    MainThread:1624 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
inThread:1624 [u1eg7o2s:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-12 11:29:11,913 INFO    MainThread:1624 [u1eg7o2s:run_manager.py:shutdown():1057] shutting down system stats and metadata service
