/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/torch/nn/modules/loss.py:431: UserWarning: Using a target size (torch.Size([100, 1])) that is different to the input size (torch.Size([100, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/torch/nn/modules/loss.py:431: UserWarning: Using a target size (torch.Size([32, 1])) that is different to the input size (torch.Size([32, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "main.py", line 353, in <module>
    main()
  File "main.py", line 298, in main
    model.train(train_data, config, val_func=val_model)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/models/cganmse.py", line 179, in train
    evaluation_vals = val_func(self, epoch_i)
  File "main.py", line 296, in val_model
    config=config, epoch_i=epoch_i)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/evaluation.py", line 27, in evaluate_model
    evaluation_vals = model.eval(data, config, use_best_kernel_scale=testing)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/models/cganmse.py", line 271, in eval
    kernel_scale=ks)
  File "/home/jupyter/papers/regressGAN/replication/CGAN/utils.py", line 80, in kde_eval
    (shape_y[0], config["eval_samples"], shape_y[1]))
RuntimeError: shape '[876, 200, 2]' is invalid for input of size 175200
